services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: api-test-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api-test-demo:
    build:
      context: ../..
      dockerfile: api-test-demo/docker/Dockerfile
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/api-test-db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8082:8082"

