openapi: 3.0.0
servers:
  - description: APIHub API Auto Mocking Scheduling and Listing court-schedule
    url: https://virtserver.swaggerhub.com/HMCTS-DTS/api-cp-crime-schedulingandlisting-courtschedule/0.0.0

info:
  title: Common Platform API Scheduling and Listing Court Schedule
  description: Scheduling and Listing API providing the court schedule
  version: 0.0.0
  contact:
    email: no-reply@hmcts.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

paths:
  /example/{example_id}:
    get:
      description: Get example for example_id
      operationId: getExampleByExampleId
      tags:
        - examples
      parameters:
        - in: path
          name: example_id
          required: true
          description: Unique id for the example - long
          schema:
            type: integer
            format: int64

      responses:
        '200':
          description:  Examples found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExampleResponse"

components:
  schemas:
    ExampleResponse:
      description: Details of examples associated with the example id
      type: object
      properties:
        exampleId:
          description: Id of the example - long
          type: integer
          format: int64
        exampleText:
          description: Information associated with the example id
          type: string
          example: "Some text"
